### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by SwoopDrew** [patchzyy/WheelWizard#11]
Hello, when i boot up my wheel wizard and it comes up with only 4 options of resolution and the cap is 1440p and i have a 4k monitor. Would there be a way to have an option for 4k?
<img width="313" alt="2024-07-14 14_58_51-Wheel Wizard" src="https://github.com/user-attachments/assets/587829a5-7609-4f72-9aaf-a2df3006c217">

**Comment by patchzyy** [comment]
yes, coming in one of the updates, once we have a dropdown component in the program it will go to 4K/6x

**Comment by SwoopDrew** [comment]
Thank you for the response, for now I'm happy to play on dolphin till the update is released.
