### ISSUE TITLE
Extremely slow download speed when downloading Retro Rewind

### ISSUE THREAD

**Issue by CrackersTie36** [patchzyy/WheelWizard#17]
When I downloaded Retro Rewind the ave speed was ~0.10 MB/s, That's slow!

**Comment by patchzyy** [comment]
Download speed may vary, especially during these times where people are working on the servers. sorry about that but i will close this since its not "really" an issue

**Comment by CrackersTie36** [comment]
> Download speed may vary, especially during these times where people are working on the servers. sorry about that but i will close this since its not "really" an issue

Ay fair, but I don't know where to find the server owner/s so yea sorry if this post i guess, botherd you
