### ISSUE TITLE
Cant Connect Lobby

### ISSUE THREAD

**Issue by tangoman64** [patchzyy/WheelWizard#18]
Hi I recently got this mod and have been enjoying it for about a week, however last night I went to search for a lobby and a just got stuck on the 'searching for opponents' screen. I thought I must require a update so I left it. I came to play today I opened wheel wizard and no update was required, I have been trying for hours to get in a lobby but to no success. I can connect to WFC fine I'm just stuck on the searching screen seeming like I will never find a lobby. its like I have been shadow banned and I cant connect to any lobby but I'm not a hacker I swear lmao. is there any reason I cant find a lobby but can still get online, and is there a way I can fix this and play because I'm itching too.

**Comment by patchzyy** [comment]
Please refer any in-game questions to ZPl's [discord ]( https://discord.gg/jczByGAqb6)as we only handle launching the game.
