### ISSUE TITLE
False positive Trojan Virus on download

### ISSUE THREAD

**Issue by Whailed** [patchzyy/WheelWizard#19]
I downloaded the latest wheel wizard file (1.2.0 WheelWizard.exe 88.2 MB) and when I run the program, my antivirus (kaspersky) catches that there is a trojan file downloaded. What the fuck dude

**Comment by patchzyy** [comment]
If you dont fully trust the program, you may always look through the source-code, run the build.bat yourself and run it through the same anti-virus (it will trigger the same triggers)
