### ISSUE TITLE
some options are covered by the taskbar

### ISSUE THREAD

**Issue by Lilicogamer13** [patchzyy/WheelWizard#23]
some options are covered by the taskbar, i using win11, so i cannot move the position of the taskbar, the github, discord, ko-fi options and some rooms and players in the player list(of the room) are covered.

**Comment by patchzyy** [comment]
We are aware of this, this is because of your windows display scaling settings being higher than 100%
Will solve this issue once we have resolved it

**Comment by Lilicogamer13** [comment]
but i using display scaling that is less then 100%, i tryied 50%(via third party apps) and 100%, no one of these worked

**Comment by Lilicogamer13** [comment]
but my display scaling is not higher than 100%

**Comment by Lilicogamer13** [comment]
possible resolve for the code(in app.xaml.cs):

using CT_MKWII_WPF.Services.Installation;
using System.Diagnostics;
using System.IO;
using System.Windows;
using MessageBox = System.Windows.Forms.MessageBox;

namespace CT_MKWII_WPF
{
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            AutoUpdater.CheckForUpdatesAsync();

            // Get the MainWindow instance
            MainWindow mainWindow = (MainWindow)MainWindow;

            // Set the Topmost property to true
            mainWindow.Topmost = true;
        }
    }
}

**Comment by WantToBeeMe** [comment]
The next release this should all be fixed

**Comment by WantToBeeMe** [comment]
Or at least, there should be an option to change the window size, which in turn should solve it
