### ISSUE TITLE
installing then not installing

### ISSUE THREAD

**Issue by PolaricPotato** [patchzyy/WheelWizard#5]
- download everything, and i get to a point where the retro rewind update bar is full but not going away so i close it assuming it was a glitch
- main page says it needs to update
- when i click it, it says rewind isnt installed, then says that it IS installed
- nothing changes and it still says it needs to update

![3](https://github.com/patchzyy/WheelWizard/assets/137445350/31821916-9758-4ed4-afb3-fe05a41e68d4)
![2](https://github.com/patchzyy/WheelWizard/assets/137445350/25c67b6c-ea87-47b4-8276-5436f4c40ebe)
![1](https://github.com/patchzyy/WheelWizard/assets/137445350/49467bba-bbfe-4425-97ff-dac3bed0e0b2)

**Comment by patchzyy** [comment]
I will look into this, please in the meantime follow these steps:

1. Go to your settings tab
2. copy your dolphin user path (bottom file path)
3. navigate to this folder in your file explorer
4. open up the /load folder
5. open up the Riivolution folder
6. removed everything inside and restart wheel wizard

**Comment by patchzyy** [comment]
This should be resolved now, changed installation logic. if not please let us know by making a new ticket
