### ISSUE TITLE
App quits when saving directories for setup

### ISSUE THREAD

**Issue by raviolei** [patchzyy/WheelWizard#6]
trying to set the path to the MkWii ISO and Dolphin and when I hit to save the app simply turns off. When I turn it on again it asks for the same stuff as if it didn't save. the ISO is on a folder on my desktop and Dolphin is in my program files, is there a certain location they have to be in for WW to read it and not die?

**Comment by TheSubMatrix** [comment]
I am seeing similar behavior

**Comment by Cosmican259** [comment]
Same with me. I seem to have found all the correct game ISO and Dolphin executable files, but it keeps crashing and not saving.

**Comment by Shorakyn** [comment]
This happened to me when I attempted to set config through the Home menu.
I was able to get around it by setting config through the settings menu

**Comment by DecoDragon** [comment]
1.0.8 seems to fix the issue at least for me but now after clicking the install button it closes. Unsure if this should be a new issue or not.

**Comment by Cosmican259** [comment]
Again, same with me. With another patch comes another problem.

**Comment by patchzyy** [comment]
we are aware and working on a patch, in the meantime use version 1.0.6

**Comment by patchzyy** [comment]
Resolved, fixed both the crashing on saving and on installing :) Thanks for reporting
