### ISSUE TITLE
Communication Error 86420

### ISSUE THREAD

**Issue by hackopo** [patchzyy/WheelWizard#8]
Hi,
If i try to get online i connect to wiilink succesfully, i appear in rooms but i only get Error 86420. i know it has something to do with my Router but i am not allowed to switch settings in it. I get the same Error with a Hotspot over mobile data. What can i do? I wanna play online so bad : C
Thanks!

**Comment by patchzyy** [comment]
Please refer any in-game questions to the discord of either [ZPL[(https://discord.gg/jczByGAqb6) (creator of RR) or [Wheel Wizard](https://discord.gg/mp264jt6TU)
