### ISSUE TITLE
license

### ISSUE THREAD

**Issue by EmeraldSnorlax** [patchzyy/WheelWizard#9]
i've noticed that this repo is missing a license. what license is this project under? picking one is crucial to ensure that others can contribute to this project -- without a license, this project is under an [implied all rights reserved copyright](https://choosealicense.com/no-permission/).

if you're totally stuck, https://choosealicense.com/ is a good place to start. just make sure that all previous contributors agree to relicense their work under the new license you pick :)

(i'm not a lawyer)

**Comment by WantToBeeMe** [comment]
Give us a few days :)
